from pathlib import Path
import argparse,shutil
p=argparse.ArgumentParser();p.add_argument('--project',type=Path,default=Path('.'));args=p.parse_args();ROOT=Path(__file__).resolve().parent;assets=args.project/'app/src/main/assets'
def change(s,old,new):
 if old not in s:raise ValueError('Missing marker '+old[:100])
 return s.replace(old,new)
s=(assets/'v011.js').read_text()
s=change(s,'const imgZH=p=>ZhDisplay.info(state.map,p,state.showEnglishNames!==false);','const imgZH=p=>p.isPlan?{title:p.title,where:p.title,action:p.note,heading:"社区地图"}:ZhDisplay.info(state.map,p,state.showEnglishNames!==false);')
s=change(s,"renderIndex($('preview'),false);}","renderIndex($('preview'),false);renderNavigation();}")
s=change(s,"$('photoLocation').textContent=imgZH(p).title;$('photoCaption').textContent=imgZH(p).action;","$('photoLocation').textContent='位置：'+imgZH(p).where+(routeFor(p)?'\\n怎么找：'+routeFor(p).text:'');$('photoCaption').textContent='操作：'+imgZH(p).action;renderPointPlans(p);")
s=change(s,"$('tutorialBody').scrollTop=0;requestAnimationFrame(()=>$('tutorialBody').scrollTop=0);}","renderStepExtras();$('tutorialBody').scrollTop=0;requestAnimationFrame(()=>$('tutorialBody').scrollTop=0);}")
s=change(s,' · 点击查看位置和操作 · 保留原图比例',' · 位置和操作直接显示 · 点击只用于放大')
s=change(s,'<b>${esc(imgZH(im).title)}</b></span>`;','<b>${esc(imgZH(im).title)}</b></span><div class="thumbContext">${positionMarkup(im)}<p><b>用途／操作：</b>${esc(imgZH(im).action)}</p></div>`;')
s=change(s,'function openImage(im,fromGallery=false){\n viewerFromGallery=fromGallery===true;','function openImage(im,fromGallery=false){\n viewerAtlas=!!im.isPlan;viewerSection=null;\n viewerFromGallery=!viewerAtlas&&fromGallery===true;')
s=change(s,'viewerList=viewerFromGallery?guide().images.slice():photos.filter','viewerList=viewerAtlas?plansForMap().slice():viewerFromGallery?guide().images.slice():photos.filter')
a=s.index(" const pane=$('viewerPane');",s.index('function openImage('));b=s.index(' drawImage();',a);s=s[:a]+s[b:]
s=change(s,' const im=viewerList[viewerPos],help=imageHelp(im),cn=imgZH(im);currentImage=im;',' const im=viewerList[viewerPos];currentImage=im;if(im.isPlan){renderPlanInfo(im);return;}const help=imageHelp(im),cn=imgZH(im);')
s=change(s,"$('imageWhere').textContent='位置：'+cn.where;$('imageWhere').hidden=cn.where===cn.title;","$('imageWhere').textContent='位置：'+cn.where+(routeFor(im)?'\\n怎么找：'+routeFor(im).text:'');$('imageWhere').hidden=false;")
s=change(s,'适应宽度时左右滑动切图；放大后滑动查看细节，底部按钮仍可切图。','图片、文字和空白区域均可左右滑动切图；放大后的图片区域保留拖动看细节。')
s=change(s,"$('imageBack').textContent=viewerFromGallery?'返回图片库原位置':'返回当前步骤';","$('imageBack').textContent=viewerSection?'返回当前资料小节':viewerFromGallery?'返回图片库原位置':'返回当前步骤';let btn=$('viewerMap');if(!btn){btn=document.createElement('button');btn.id='viewerMap';btn.className='wide';$('fullCaption').before(btn);}btn.textContent='查看该图的地图与楼层';btn.onclick=()=>openAtlas(false);")
s=change(s,"$('viewerScope').textContent=viewerFromGallery?'完整图片库':'当前阶段';","$('viewerScope').textContent=viewerAtlas?'地图与楼层':viewerSection?'当前资料小节':viewerFromGallery?'完整图片库':'当前阶段';")
s=change(s,' if(!viewerFromGallery)photoIndex=viewerPos;',' if(!viewerFromGallery&&!viewerAtlas&&!viewerSection)photoIndex=viewerPos;')
s=change(s,'function closeImage(){const from=viewerFromGallery;','function closeImage(){if(viewerAtlas){galleryCleanup();viewerAtlas=false;openAtlas(true);return;}if(viewerSection){const id=viewerSection;galleryCleanup();viewerSection=null;openSourceSection(id);return;}const from=viewerFromGallery;')
s=change(s,"function closeAnyModal(){if(['image','image-gallery'].includes(modalKind))","function closeAnyModal(){if(modalKind==='atlas'){closeAtlas();return;}if(modalKind==='source-section'){showSourceIndex();return;}if(['image','image-gallery'].includes(modalKind))")
s=change(s,'window.GuideDebug={goMap,',(ROOT/'extension.js').read_text()+'\nwindow.GuideDebug={openAtlas,showSourceIndex,openSourceSection,goMap,')
(assets/'v012.js').write_text((ROOT/'labels.js').read_text()+'\n'+s);(assets/'v012.css').write_text((assets/'v010.css').read_text()+'\n'+(ROOT/'style.css').read_text());shutil.copyfile(ROOT/'details.js',assets/'details.js')
s=(assets/'index.html').read_text();s=change(s,'v0.11 · 中文主导版','v0.12 · 地图定位版');s=change(s,'href="v010.css"','href="v012.css"')
s=change(s,'<button id="galleryOverview">查看本图全部原图</button>','<button id="galleryOverview">图文点位库（位置直接显示）</button><button id="atlasOverview">地图与楼层定位</button><button id="sourceOverview">原攻略章节对照／完整原文</button>')
s=change(s,'<section id="photoSection"','<section class="card" id="stepDetails" hidden></section><div id="routeActions" class="routeActions"></div><button id="sourceStep" class="wide">原攻略章节对照（含前置制作）</button><section id="photoSection"')
s=change(s,'<div class="photoFrame">','<p id="photoLocation" class="photoLocation"></p><div id="pointMapLinks"></div><div class="photoFrame">');s=change(s,'</div><p id="photoLocation" class="photoLocation"></p><p id="photoCaption"','</div><p id="photoCaption"')
s=change(s,'<section id="noPhoto"','<details id="pointListWrap" class="card" hidden><summary>本阶段全部位置文字</summary><div id="pointList"></div></details><section id="noPhoto"')
s=change(s,'<script src="v011.js"></script>','<script src="navigation.js"></script><script src="source-index.js"></script><script src="details.js"></script><script src="v012.js"></script>');(assets/'index.html').write_text(s)
f=args.project/'app/build.gradle';s=f.read_text();s=change(s,'versionCode 11','versionCode 12');s=change(s,"versionName '0.11'","versionName '0.12'");f.write_text(s)
f=args.project/'app/src/main/AndroidManifest.xml';s=f.read_text();s=change(s,'    <application','    <uses-permission android:name="android.permission.INTERNET" />\n    <application');s=change(s,'        <activity\n            android:name=".MainActivity"','        <activity android:name=".ReaderActivity" android:exported="false" />\n        <activity\n            android:name=".MainActivity"');f.write_text(s)
f=args.project/'app/src/main/java/com/openai/cod15guide/MainActivity.java';s=f.read_text();s=change(s,'if ("https".equals(uri.getScheme())) {','if (ReaderActivity.trusted(uri)) {\n                    startActivity(new Intent(MainActivity.this, ReaderActivity.class).setData(uri));return true;\n                }\n                if ("https".equals(uri.getScheme())) {');f.write_text(s);shutil.copyfile(ROOT/'ReaderActivity.java',f.parent/'ReaderActivity.java')
print('Applied v0.12; package, signing identity and progress storage preserved.')
