// Navigation and source-detail layer. File coverage is not text completeness.
let atlasReturn=null,atlasScroll=0,viewerAtlas=false,viewerSection=null,activeSourceSection=null;
const plansForMap=()=> (NAVIGATION.plans[state.map]||[]);
const sourceDoc=()=> SOURCE_INDEX.maps[state.map]||null;
const sourceLink=(section)=>{const d=sourceDoc();return d?d.url+(section?.anchor?'#'+section.anchor:''):null;};
const externalLink=(url,label)=>url?`<a class="sourceLink" href="${esc(url)}">${esc(label)}</a>`:'';
function routeFor(p){const rules=NAVIGATION.routes[state.map]||[];return rules.find(r=>r.indices?.includes(p.index))||rules.find(r=>r.match&&new RegExp(r.match,'i').test((p.caption||'')+' '+(p.last_heading||'')))||null;}
function positionMarkup(p){const inf=imgZH(p),r=routeFor(p);return `<p class="pointWhere"><b>位置：</b>${esc(inf.where||inf.title)}</p>${r?`<p class="pointRoute"><b>怎么找：</b>${esc(r.text)}</p>`:''}`;}
function plansMarkup(){const p=plansForMap();return `<button class="wide routeButton" data-open-atlas>地图与楼层定位${p.length?' · '+p.length+'张':' · 查来源'}</button>`;}
function bindAtlasButtons(root){root.querySelectorAll('[data-open-atlas]').forEach(b=>b.onclick=()=>openAtlas(false));}
function sourceMatch(section){const doc=guide();return doc?doc.images.filter(p=>section.images.includes(p.index)):[];}
function currentSections(){const doc=sourceDoc();if(!doc)return[];const ids=new Set(photos.map(p=>p.index));return doc.sections.filter(s=>s.images.some(i=>ids.has(i))&&s.level>=3);}
function sectionFacts(section){const d=sourceDoc(),key=d?.guide+'|'+section.heading;if(DETAIL_FACTS.sections[key])return DETAIL_FACTS.sections[key];return [...new Set(sourceMatch(section).map(p=>imgZH(p).action).filter(t=>t&&!t.includes('尚未核实')))];}
function sourceCoverageNotice(){return '中文步骤是整理说明，不是原网页逐字复制。完整原文在作者网页阅读；这里保留章节对照与原图，不用“有图”冒充“正文已补全”。';}
function renderNavigation(){const src=sourceDoc(),m=plansForMap();$('atlasOverview').textContent=m.length?`地图与楼层定位 · ${m.length}张`:'地图与楼层定位 / 来源';$('sourceOverview').disabled=!src;$('sourceNote').textContent=guide()?`来源配图 ${guide().images.length} 张 · ${m.length} 张已接入的社区地图。中文正文为整理版；完整性请查看“原攻略章节对照”，不以图片数量代替文字核对。`:'这张地图暂未关联主线图文资料。现有生存说明不等于完整社区攻略。';}
function renderStepExtras(){
 const box=$('stepDetails'),src=sourceDoc(),extra=DETAIL_FACTS.steps[state.map]?.[state.step]||[];box.innerHTML='';
 if(extra.length){const h=document.createElement('h2');h.textContent='逐项操作';box.append(h);const ol=document.createElement('ol');ol.className='actionList';extra.forEach(t=>{const li=document.createElement('li');li.textContent=zh(t);ol.append(li);});box.append(ol);}
 const sections=currentSections();if(sections.length){const p=document.createElement('p');p.className='muted';p.textContent='本阶段的制作、升级和分支细项：';box.append(p);for(const sec of sections){const b=document.createElement('button');b.className='detailJump';b.textContent=ZhDisplay.heading(sec.heading)+' · '+sec.images.length+'张图';b.onclick=()=>openSourceSection(sec.id);box.append(b);}}
 box.hidden=!extra.length&&!sections.length;$('routeActions').innerHTML=plansMarkup()+externalLink(src?.url,'阅读原作者完整攻略（联网）');bindAtlasButtons($('routeActions'));$('sourceStep').disabled=!src;$('pointList').innerHTML='';
 if(photos.length){const seen=new Set();photos.forEach(p=>{const key=p.file+':'+p.index;if(seen.has(key))return;seen.add(key);const item=document.createElement('div');item.className='pointText';item.innerHTML=`<span class="pointNumber">${p.index+1}</span><div>${positionMarkup(p)}</div>`;$('pointList').append(item);});}
 $('pointListWrap').hidden=!photos.length;$('stepSource').innerHTML=src?externalLink(src.url,'原作者完整图文：COD Zombies Guides')+'<br>社区配图和本地整理说明分别标注；随机答案以本局为准。':'此图还没有已核实的主线图文来源。';
}
function showSourceIndex(){
 const doc=sourceDoc();if(!doc){toast('本版未接入该图原攻略。');return;}galleryCleanup();showModal('原攻略章节对照 · '+D[state.map].name,'sources');
 const intro=document.createElement('div');intro.className='notice';intro.textContent=sourceCoverageNotice();$('modalBody').append(intro);const a=document.createElement('a');a.className='sourceLink wide';a.href=doc.url;a.textContent='阅读原作者完整图文（联网）';$('modalBody').append(a);
 for(const sec of doc.sections){const b=document.createElement('button');b.className='sourceChapter level'+sec.level;const detail=DETAIL_FACTS.sections[doc.guide+'|'+sec.heading],txt=sectionFacts(sec);b.innerHTML=`<b>${esc(ZhDisplay.heading(sec.heading))}</b><small>${detail?'已补充中文细项':txt.length?'本地简述及点位':'原文待补入中文'} · ${sec.images.length} 张直接配图 · 原文 ${sec.startLine}–${sec.endLine} 行</small>`;b.onclick=()=>openSourceSection(sec.id);$('modalBody').append(b);}
}
function openSourceSection(id){
 const doc=sourceDoc(),sec=doc?.sections.find(s=>s.id===id);if(!sec)return;galleryCleanup();activeSourceSection=id;showModal(ZhDisplay.heading(sec.heading),'source-section');const top=document.createElement('div');top.innerHTML=externalLink(sourceLink(sec),'阅读原文这一节（含全部文字／视频链接）');$('modalBody').append(top);
 const facts=sectionFacts(sec);if(facts.length){const ol=document.createElement('ol');ol.className='actionList';facts.forEach(t=>{const li=document.createElement('li');li.textContent=zh(t);ol.append(li);});$('modalBody').append(ol);}else{const p=document.createElement('p');p.className='notice';p.textContent='这节原文的完整中文细项尚未接入；没有用一句泛泛的提示伪装成已完成。可直接打开上面的原文。';$('modalBody').append(p);}
 const ims=sourceMatch(sec);ims.forEach(im=>{const card=document.createElement('article');card.className='sourcePoint';card.innerHTML=`<img src="${esc(im.file)}" loading="lazy" width="${im.width}" height="${im.height}" alt="${esc(im.caption)}">${positionMarkup(im)}<p><b>操作：</b>${esc(imgZH(im).action)}</p>`;card.querySelector('img').onclick=()=>{openImage(im,true);viewerSection=id;viewerAtlas=false;viewerList=ims.slice();viewerPos=ims.findIndex(p=>p.index===im.index);drawImage();};$('modalBody').append(card);});
 const nested=doc.sections.filter(s=>s.parent===sec.id);if(nested.length){const h=document.createElement('h2');h.textContent='展开子章节';$('modalBody').append(h);nested.forEach(s=>{const b=document.createElement('button');b.className='detailJump';b.textContent=ZhDisplay.heading(s.heading);b.onclick=()=>openSourceSection(s.id);$('modalBody').append(b);});}
 const b=document.createElement('button');b.className='wide';b.textContent='返回原攻略章节目录';b.onclick=showSourceIndex;$('modalBody').append(b);
}
function openAtlas(restore=false){
 if(!restore){atlasReturn={kind:modalKind,section:activeSourceSection,image:currentImage,viewerPos,viewerList:viewerList?.slice(),fromGallery:viewerFromGallery,viewerSection,scroll:$('modalBody').scrollTop};atlasScroll=0;}
 galleryCleanup();showModal('地图与楼层 · '+D[state.map].name,'atlas');const intro=document.createElement('p');intro.className='notice';intro.textContent='先找区域，再看楼层与门／楼梯连线。地图保留作者原图；房间译名是对照名称，图片中的朝向不等于你当前面朝的方向。';$('modalBody').append(intro);const list=plansForMap();
 if(!list.length){const p=document.createElement('p');p.textContent='本版尚未接入这张地图的可靠区域图，不代表社区没有。不会拿别张地图或自绘猜测代替。';$('modalBody').append(p);}
 const glossary=document.createElement('details');glossary.className='card';glossary.innerHTML='<summary>地图常见英文图例对照</summary><p>Ground Floor：底层；1st Floor：上一层（英国楼层叫法）；Stairs：楼梯；Door：门；Spawn：出生区／出怪点，需结合图例；Power：电源；Part：部件；Pack-a-Punch：武器强化机。</p>';$('modalBody').append(glossary);
 list.forEach(im=>{const article=document.createElement('article');article.className='planCard';article.innerHTML=`<h2>${esc(im.title)}</h2><img src="${esc(im.file)}" loading="lazy" width="${im.width}" height="${im.height}" alt="${esc(im.title)}"><p>${esc(im.note||'对照原图中的门、楼梯和通向相邻区域的标签。')}</p>${externalLink(im.sourceUrl,'地图来源与作者说明（联网）')}`;article.querySelector('img').onclick=()=>openPlan(im);$('modalBody').append(article);});
 if(state.map==='bo2_buried'&&guide()){const maze=guide().images.find(p=>p.index===13);if(maze){const b=document.createElement('button');b.className='wide';b.textContent='另看主线攻略的迷宫布局变体图';b.onclick=()=>openImage(maze,true);$('modalBody').append(b);}}
 (NAVIGATION.links[state.map]||[]).forEach(x=>{const p=document.createElement('p');p.innerHTML=externalLink(x.url,x.title);$('modalBody').append(p);});const close=document.createElement('button');close.className='wide';close.textContent='返回刚才的位置';close.onclick=closeAtlas;$('modalBody').append(close);if(restore){$('modalBody').scrollTop=atlasScroll;requestAnimationFrame(()=>$('modalBody').scrollTop=atlasScroll);}
}
function openPlan(im){atlasScroll=$('modalBody').scrollTop;openImage(im,false);viewerAtlas=true;viewerSection=null;viewerList=plansForMap().slice();viewerPos=viewerList.findIndex(x=>x.id===im.id);drawImage();}
function renderPlanInfo(im){
 $('imageWhere').hidden=true;$('imageMeta').textContent=D[state.map].name+' · 社区地图';$('fullPlace').textContent=im.title;$('fullAction').textContent=im.note||'先定位图中房间名称，再沿门、楼梯和区域连接线找入口。此图不是实时导航，不会读取你的游戏坐标。';$('fullCaption').textContent='文字区与空白区也能左右滑动切图；放大后的图片区域拖动用于查看细节。';$('imageBranch').hidden=true;$('branchWarning').hidden=true;$('originalCaption').textContent=im.originalTitle||im.title;$('provenance').innerHTML=externalLink(im.sourceUrl,'查看该地图的原作者页面')+'<br>'+esc(im.date||'')+' · 原图署名保持不变';$('glossaryToggle').hidden=true;$('imageBack').textContent='返回地图目录';$('viewerNumber').textContent=(viewerPos+1)+' / '+viewerList.length;$('viewerScope').textContent='地图与楼层';
}
function closeAtlas(){const r=atlasReturn;atlasReturn=null;galleryCleanup();hideModal();if(!r)return;if(r.kind==='source-section'&&r.section)openSourceSection(r.section);else if(r.kind==='sources')showSourceIndex();else if(['image','image-gallery'].includes(r.kind)&&r.image&&!r.image.isPlan){openImage(r.image,r.fromGallery);viewerSection=r.viewerSection;viewerList=r.viewerList;viewerPos=r.viewerPos;drawImage();$('modalBody').scrollTop=r.scroll;}else if(r.kind==='gallery'){openGallery(true);$('modalBody').scrollTop=r.scroll;}}
function installFullPageSwipe(){
 let start=null;const host=$('modal');
 host.addEventListener('touchstart',e=>{if(!host.classList.contains('imageMode')||e.touches.length!==1){start=null;return;}const t=e.target;if(t.closest('button,input,select,textarea,a,summary')){start=null;return;}if(zoom>1&&t.closest('.viewerPane')){start=null;return;}start={x:e.touches[0].clientX,y:e.touches[0].clientY,locked:false};},{passive:true});
 host.addEventListener('touchmove',e=>{if(!start||e.touches.length!==1){start=null;return;}const dx=e.touches[0].clientX-start.x,dy=e.touches[0].clientY-start.y;if(!start.locked&&Math.abs(dy)>18&&Math.abs(dy)>Math.abs(dx)){start=null;return;}if(Math.abs(dx)>18&&Math.abs(dx)>Math.abs(dy)*1.5){start.locked=true;if(e.cancelable)e.preventDefault();}},{passive:false});
 host.addEventListener('touchend',e=>{if(!start||e.changedTouches.length!==1){start=null;return;}const dx=e.changedTouches[0].clientX-start.x,dy=e.changedTouches[0].clientY-start.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5)moveImage(dx<0?1:-1);start=null;},{passive:true});host.addEventListener('touchcancel',()=>start=null,{passive:true});
}
function pointPlans(p){const list=plansForMap(),r=routeFor(p);if(r?.planDocs)return list.filter(im=>r.planDocs.includes(im.doc));return list.length<=4?list:[];}
function renderPointPlans(p){const box=$('pointMapLinks');box.innerHTML='';const related=pointPlans(p);related.slice(0,5).forEach(im=>{const b=document.createElement('button');b.className='pointPlan';b.dataset.planId=im.id;b.textContent='区域图：'+im.title;b.onclick=()=>{openAtlas(false);openPlan(im);};box.append(b);});if(!related.length&&plansForMap().length){const b=document.createElement('button');b.className='pointPlan';b.textContent='查看本图区域／楼层目录';b.onclick=()=>openAtlas(false);box.append(b);}}
$('atlasOverview').onclick=()=>openAtlas(false);$('sourceOverview').onclick=showSourceIndex;$('sourceStep').onclick=showSourceIndex;installFullPageSwipe();
