// Source-only headings were not present in the old picture-caption dictionary.
Object.assign(ZH_LOCALE.headings,{
'Trial By Ordeal':'主线：磨难试炼','Requirements':'前置要求','Recommended Class Setups':'推荐配置','Recommended Elixirs':'推荐药剂','Step 3: Complete the Three Questlines':'第3步：完成三条任务线','Obtaining the Alistair\'s Annihilator':'制作阿利斯泰尔歼灭者','Video Guides':'视频攻略','Credits':'作者与鸣谢','Tower of Babble':'主线：巴别塔','Explosive Kills':'爆炸击杀','Salvation Lies Above':'主线：上方的救赎','Step 3: Acquire the Vessel':'第3步：取得容器','Recommended Gobblegums':'推荐泡泡糖','Recommended GobbleGums':'推荐泡泡糖','Electromagnetic Awakening Party':'主线：电磁觉醒','Step 4: Preserve the Integrity of our Mission':'第4步：完成使命保护环节','Most Escape Alive':'主线：逃出监狱','Abandon Ship':'主线：弃船','Poison Lockdown':'毒元素封锁挑战','Water Lockdown':'水元素封锁挑战','Electric Lockdown':'电元素封锁挑战','Fire Lockdown':'火元素封锁挑战','Little Lost Girl':'主线：迷失的小女孩','Step 3: Rain Fire':'第3步：天降火雨','Step 4: Unleash the Horde':'第4步：释放敌群','Main Quest':'主线任务','Greek Tragedy':'主线：希腊悲剧','Step 1: Ignite the Beacons':'第1步：点燃信标','Step 4: Scepter and Sundial':'第4步：权杖与日晷','Seeds of Doubt':'主线：疑虑之种','Step 2: Collecting the Cogs':'第2步：收集齿轮','Casimir Mechanism':'主线：卡西米尔机制','Apocalypse Averted':'主线：阻止末日','Step 1: The Beginning of the End':'第1步：开启仪式流程','Mined Games':'主线：埋葬','Round Infinity':'无限回合搜尸','Love and War':'主线：爱与战争','Step 4: Collecting the Trophies':'第4步：收集奖杯','High Maintenance':'主线：高层维护','Ballistic Knife Step':'弹道刀环节','For the Good of All':'主线：为了所有人','Step 2: Collect the Audio Reels':'第2步：收集录音带','Step 5: Acquire the Apothicon Eggs':'第5步：收集阿波西康蛋','Step 6: Collect the Runes of Creation':'第6步：收集创世符文','Ensemble Cast':'主线：全体演员','Venerated Warrior':'主线：受敬重的战士','Step 2: Purge the Blight':'第2步：清除腐化','Pop Goes The Weasel':'主线：黄鼠狼的结局','Building the Plane':'建造飞机','Acquiring the Skulls':'收集五个骷髅','Time Travel Will Tell':'主线：时空旅行','Water Slide Step':'滑水道环节','Repeating the Quest':'重复执行任务'
});
Object.values(SOURCE_INDEX.guides).forEach(g=>g.sections.forEach(s=>{if(/guide by/i.test(s.heading)){const name=s.heading.split(/guide by\s*/i).pop();let prefix=/solo/i.test(s.heading)?'单人视频攻略':/co-op/i.test(s.heading)?'联机视频攻略':/round 150/i.test(s.heading)?'150回合视频攻略':/black ops 2/i.test(s.heading)?'黑色行动2视频攻略':/black ops 3/i.test(s.heading)?'黑色行动3视频攻略':/black ops 1/i.test(s.heading)?'黑色行动1视频攻略':'视频攻略';ZH_LOCALE.headings[s.heading]=prefix+'（'+name+'）';}}));
Object.assign(PHOTO_RANGES,{
 bo2_buried:{0:[0,1,2,3],1:[4,5,6,7],2:[8,9],3:[10,11,12],4:[],5:[14,15,16,17,18,19],6:[20,21,22],7:[13],8:[23,24]},
 bo2_mob:{0:[0,1,2,3],1:[4,5,6,7,8,9,10,11],2:[12],3:[14,15,16,17,18,19,20,21,22,23,24,25],4:[12,13],5:[],6:[26,27,28,29,30],7:[],8:[31]},
 bo2_tranzit:{0:[],1:[],2:[0],3:[1],4:[2],5:[],6:[3,4]},
 bo2_dierise:{0:[0,1,2,3],1:[4,5,6,7],2:[8,9],3:[10],4:[],5:[11,12,13,14,15,16],6:[17],7:[18,19,20,21],8:[22,23,24,25,26,27,28,29,30,31,32,33],9:[22]}
});
ZOMBIE_DATA.bo2_mob.steps[3].title='斧头、五个骷髅与勺子前置';
